#!/bin/bash
CONTINENT=europe
declare -ga StringArray=("croatia" "slovenia")
PBF_FILE=${COUNTRY}-latest.osm.pbf
MAP_FILE=${COUNTRY}.osm.map
MF_POI_FILE=${COUNTRY}.poi
LOCUS_POI_FILE=locus-orig-${COUNTRY}.osm.db
POI_FILE=${COUNTRY}.osm.db
ROUTES_FILE=${COUNTRY}-routes.osm
MAPSFORGE_TYPE=hd
MAPSFORGE_VERSION=20211221.103531-426
OSMOSIS_VERSION=0.48.3
#https://oss.sonatype.org/content/repositories/snapshots/org/mapsforge/mapsforge-map-writer/master-SNAPSHOT/mapsforge-map-writer-master-20211209.135600-425-jar-with-dependencies.jar
